version: "3.8"
services:
    build:
        # environment:
        #     VLANG_BUILD_OPTIONS: "-prod -gc boehm_full_opt"
        #     VLANG_LAMBDA_FUNC_NAME: "main.v"
        build:
            context: .
            target: devbuild
            # args:
            #     vlang_repo_url: "https://github.com/aheissenberger/v.git"
            #     vlang_repo_branch: "feature/feat-request-timeout"
        volumes: 
            - "./src:/src:ro"
            - "./build-aws-linux:/var/task"
    lambda:
        environment: 
            - "DOCKER_LAMBDA_STAY_OPEN=1"
            - "LOG_LEVEL=info"
            - "HANDLER=default"
        build:
            context: ./tools/aws-lambda-rie
        ports:
            - "9000:8080"
        volumes: 
            - "./src:/src:ro"
            - "./build-aws-linux:/var/task"
    deploy:
        build:
            context: ./tools/serverless-framework
        volumes:
            - "~/.aws:/root/.aws"
            - "./build-aws-linux:/opt/app/src:ro"
            - "./build-serverless-package:/opt/app/build"
            - "./serverless.yml:/opt/app/config/serverless.yml:ro"
        entrypoint: 
            - "/deploy.sh"
