version: "3.8"
services:
    lambda:

        environment: 
            - "DOCKER_LAMBDA_STAY_OPEN=1"
        build:
            context: .
            target: prodbuild
        ports:
            - "9000:8080"
            #- "9001:9001" # lambda runtime api
        volumes: 
            - "./src:/src:ro"
            - "./build-docker:/var/task"

        entrypoint: 
            - "/usr/bin/aws-lambda-rie"
            - "--log-level"
            - "debug"
            #- "/var/task/bootstrap"