service: ah-vlang-test

provider:
  name: aws
  runtime: provided
  lambdaHashingVersion: 20201221
  versionFunctions: false
  region: eu-west-1
  memorySize: 128

  stage: dev

functions:
  lambda_trigger:
    handler: default
    package:
      individually: true
    events:
      - httpApi:
          path: /hello
          method: get
