service: ah-vlang-test

provider:
  name: aws
  runtime: provided
  lambdaHashingVersion: 20201221
  versionFunctions: false
  region: eu-west-1
  memorySize: 128

  stage: dev
  #region: eu

# package:
#   package:
#   individually: true
#   exclude:
#     - "*/**"
#     - "*"
#   include:
#     - build-aws-linux/**

functions:
  lambda_trigger:
    handler: build-aws-linux/bootstrap
    package:
      individually: true
    events:
      - httpApi:
          path: /hello
          method: get
