service: ah-vlang-test

configValidationMode: error
provider:
  name: aws
  runtime: provided
  lambdaHashingVersion: 20201221
  versionFunctions: false
  region: eu-west-1
  memorySize: 128

  stage: dev
  

layers:
  libraries:
    path: ./
    package:
      patterns:
        - '!bootstrap'


functions:
  lambda_trigger:
    handler: default
    layers:
      - { Ref: LibrariesLambdaLayer }
    package:
      individually: true
      patterns:
        - '!lib/**'
    events:
      - httpApi:
          path: /hello
          method: get
